spring:
  application:
    name: book-application
  security:
    user:
      name: admin
      password: password

server:
  port: 8083

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management:
  context-path: /manage