spring:
  application:
    name: central-discovery-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
  dashboard:
    enabled: true